version: "3.2"
volumes:
    prometheus-volume:
    grafana-volume:
services:
    lwrf-cfh:
        build:
            context: .
            dockerfile: Dockerfile.arm32v6
        restart: unless-stopped
        volumes:
            - ./config.yml:/app/config.yml:ro
            - ./lightwave_link.py:/app/lightwave_link.py:ro
        # Listens for UDP broadcast traffic on port 9761 (LightwaveRF responses)
        # Listens for HTTP (TCP) traffic on 9191 (prometheus exporter)
        userns_mode: host
        network_mode: host
