{
 "title": "LightwaveRF Heating",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "Room",
    "query": "query_result({job=\"lwl\",product=\"valve\"})"
   },
   {
    "name": "Switch",
    "query": "query_result({job=\"lwl\",product=\"tmr1ch\"})"
   }
  ]
 },
 "panels": [
  { "title": "Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$Switch",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "repeat": "Switch",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "lwl_output_ratio{name=\"Boiler switch\"}"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4.8, "x": 0, "y": 3 },
   "repeat": "Room",
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "lwl_output_ratio{name=\"$Room\"}"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4.8, "x": 4.8, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "lwl_output_ratio{name=\"$Room\"}"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4.8, "x": 9.6, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "lwl_output_ratio{name=\"$Room\"}"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4.8, "x": 14.399999999999999, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "lwl_output_ratio{name=\"$Room\"}"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4.8, "x": 19.2, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "lwl_output_ratio{name=\"$Room\"}"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4.8, "x": 0, "y": 6 },
   "repeat": "Room",
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "lwl_current_celsius{name=\"$Room\"} - (lwl_target_celsius{name=\"$Room\"} > 0)"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4.8, "x": 4.8, "y": 6 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "lwl_current_celsius{name=\"$Room\"} - (lwl_target_celsius{name=\"$Room\"} > 0)"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4.8, "x": 9.6, "y": 6 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "lwl_current_celsius{name=\"$Room\"} - (lwl_target_celsius{name=\"$Room\"} > 0)"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4.8, "x": 14.399999999999999, "y": 6 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "lwl_current_celsius{name=\"$Room\"} - (lwl_target_celsius{name=\"$Room\"} > 0)"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4.8, "x": 19.2, "y": 6 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "lwl_current_celsius{name=\"$Room\"} - (lwl_target_celsius{name=\"$Room\"} > 0)"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4.8, "x": 0, "y": 9 },
   "repeat": "Room",
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "expr": "lwl_battery_volts{name=\"$Room\"}"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4.8, "x": 4.8, "y": 9 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "expr": "lwl_battery_volts{name=\"$Room\"}"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4.8, "x": 9.6, "y": 9 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "expr": "lwl_battery_volts{name=\"$Room\"}"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4.8, "x": 14.399999999999999, "y": 9 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "expr": "lwl_battery_volts{name=\"$Room\"}"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4.8, "x": 19.2, "y": 9 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "expr": "lwl_battery_volts{name=\"$Room\"}"
    }
   ]
  },
  { "title": "Thermal History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "$Room",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4.8, "x": 0, "y": 13 },
   "repeat": "Room",
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "lwl_current_celsius{name=\"$Room\"}",
     "legendFormat": "Actual Temperature"
    },
    {
     "expr": "lwl_target_celsius{name=\"$Room\"}",
     "legendFormat": "Target Temperature"
    },
    {
     "expr": "lwl_output_ratio{name=\"$Room\"}",
     "legendFormat": "Output"
    },
    {
     "expr": "lwl_target_ratio{name=\"$Room\"}",
     "legendFormat": "Target Output"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4.8, "x": 4.8, "y": 13 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "lwl_current_celsius{name=\"$Room\"}",
     "legendFormat": "Actual Temperature"
    },
    {
     "expr": "lwl_target_celsius{name=\"$Room\"}",
     "legendFormat": "Target Temperature"
    },
    {
     "expr": "lwl_output_ratio{name=\"$Room\"}",
     "legendFormat": "Output"
    },
    {
     "expr": "lwl_target_ratio{name=\"$Room\"}",
     "legendFormat": "Target Output"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4.8, "x": 9.6, "y": 13 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "lwl_current_celsius{name=\"$Room\"}",
     "legendFormat": "Actual Temperature"
    },
    {
     "expr": "lwl_target_celsius{name=\"$Room\"}",
     "legendFormat": "Target Temperature"
    },
    {
     "expr": "lwl_output_ratio{name=\"$Room\"}",
     "legendFormat": "Output"
    },
    {
     "expr": "lwl_target_ratio{name=\"$Room\"}",
     "legendFormat": "Target Output"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4.8, "x": 14.399999999999999, "y": 13 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "lwl_current_celsius{name=\"$Room\"}",
     "legendFormat": "Actual Temperature"
    },
    {
     "expr": "lwl_target_celsius{name=\"$Room\"}",
     "legendFormat": "Target Temperature"
    },
    {
     "expr": "lwl_output_ratio{name=\"$Room\"}",
     "legendFormat": "Output"
    },
    {
     "expr": "lwl_target_ratio{name=\"$Room\"}",
     "legendFormat": "Target Output"
    }
   ]
  },
  {
   "title": "$Room",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4.8, "x": 19.2, "y": 13 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "lwl_current_celsius{name=\"$Room\"}",
     "legendFormat": "Actual Temperature"
    },
    {
     "expr": "lwl_target_celsius{name=\"$Room\"}",
     "legendFormat": "Target Temperature"
    },
    {
     "expr": "lwl_output_ratio{name=\"$Room\"}",
     "legendFormat": "Output"
    },
    {
     "expr": "lwl_target_ratio{name=\"$Room\"}",
     "legendFormat": "Target Output"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Call for heat: Switching on",
   "type": "graph",
   "description": "When one or more valves are calling for heat, there must be at least one switch calling for heat (i.e. the boiler switch)",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(lwl_output_ratio{product=\"valve\"} > 0)",
     "legendFormat": "Valves"
    },
    {
     "expr": "count(lwl_output_ratio{product=\"electr\"} > 0)",
     "legendFormat": "Switches"
    }
   ]
  },
  {
   "title": "Call for heat: Switching off",
   "type": "graph",
   "description": "When no valves are calling for heat, there must be any switch calling for heat (i.e. the boiler switch)",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(lwl_output_ratio{product=\"valve\"} > 0)",
     "legendFormat": "Valves"
    },
    {
     "expr": "count(lwl_output_ratio{product=\"electr\"} > 0)",
     "legendFormat": "Switches"
    }
   ]
  },
  {
   "title": "Low battery",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "lwl_battery_volts{product=\"valve\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Status updates",
   "type": "graph",
   "description": "Alert when no status updates are received",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "Status update count (6h)" }
   ],
   "targets": [
    {
     "expr": "changes(lwl_time{product=\"valve\"}[3h])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Transmit failures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(lwl_transmit_failures_total[5m])  "
    }
   ]
  }
 ]
}